fail_fast: false

repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: uv
        args: ['run', 'ruff', 'format']
        types: [python]
        language: system
      - id: mypy
        name: mypy
        entry: uv
        args: ['run', 'mypy']
        # note -- the below may preclude the use of a GUI Git client
        language: system
        types: [python]
        require_serial: true

      - id: lint
        name: lint
        entry: uv
        args: ['run', 'ruff', 'check', '--fix']
        language: system
        types: [python]
        require_serial: true