name: Release to PyPI

on:
  push:
    branches: [main]
  # Trigger on manual dispatch
  # This allows you to manually trigger the workflow from the GitHub Actions UI
  # Useful for releasing versions without a new commit
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.13.3"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Run tests
        run: uv pip install pytest && pytest
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv publish --token $PYPI_TOKEN --publish-url https://upload.pypi.org/legacy/